sudo: false
language: node_js

node_js:
  - "5"
  - "6"

services:
  - mongodb

env:
  - CXX=g++=4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  code_climate:
      repo_token: 5bee24bb461a5e7bfa579d241446a0153a157662

after_success:
   - npm run coveralls